### ISSUE TITLE
[moqups] A/C unit info screen

### ISSUE THREAD

**Issue by ranilplus** [ranilplus/Idac-Maintaenance#10]

**Comment by AthulaDissanayaka** [comment]
How can I See the mockup?

**Comment by ranilplus** [comment]
![ac unit](https://cloud.githubusercontent.com/assets/11794251/9566125/1c96783a-4f14-11e5-8b3d-278fa12c5319.png)

**Comment by ranilplus** [comment]
URL: http://arclanka.com/idac/
