### ISSUE TITLE
Discussion on 03 October

### ISSUE THREAD

**Issue by AthulaDissanayaka** [ranilplus/Idac-Maintaenance#11]
Please do the following by 10/10/2015 as agreed.
1. Create DB for customer and units.
2. Customer name in customer screen should have two fields. I think we should have the second field as Location. Save as two fields but in units screen merge both fields and show as owner.
3. Complete customer and units to add/update/delete also the print button to print details entered.
4. Add new button as SERVICE
5. Change as District in Customer Screen..  
![customer screen](https://cloud.githubusercontent.com/assets/13131462/10262148/3cec73ac-69d9-11e5-9394-35163e7b491b.JPG)
6. Change as Breakdowns in dashboard
![dashboard](https://cloud.githubusercontent.com/assets/13131462/10262175/ce6fbcb2-69d9-11e5-8cb3-ec0771c10a8c.JPG)

Please let me know if you have any other suggestions.

**Comment by ranilplus** [comment]
2,4,5,6 fixed

**Comment by AthulaDissanayaka** [comment]
1. Creation of db is very important by Friday.
2. We should have a header for the second field as 'Location'. 
3. This is also important with item 1.
4. According to Samantha we should call the new button SERVICE.
   5 and 6 are ok.
   Major part is 1 and 3. Please attend asap. I mean before Friday.

**Comment by ranilplus** [comment]
4 fixed,
2, we can't use it as location because city field is given below. new one is for 2nd part of customer name if available, Ex [Sampath bank] [ Super grade], [sampath bank] [ Metro],  [sampath bank], [KCC], [Sampath bank] [head office]

**Comment by AthulaDissanayaka** [comment]
Ok, let the user decide and come with something. Until then we leave it blank. My  main worry is no. 1 ???.
I hope this time you finish on time of your commitment. So far you have completed simple ones.
Thanks

**Comment by ranilplus** [comment]
l'm facing an issue when transferring sample db to webhosting space need time to investigate more. due to limited resources on web memory,cashing,firewall, maybe windows vs linux.  dev environment(widows) is ok without print function. i'll find a solution and fix it today.

**Comment by AthulaDissanayaka** [comment]
Thanks for the update. I went through the customer option. Good job. There are some changes I need to fine tune.
1. When you find customer by entering blank field, I want the result screen limited to 5 or 10 and it should have the facility to roll up and down on the result list.
2. The customer names should be on name order.
3. Customer find works only for blank field. It should work as if I enter 'S' it should display all names starting with 'S'
4.  When I go through the list I should be able to enter from the list itself to go to the details.
5. We have to think of something to do with the second customer name for easy identification from the list. We will discuss this at the next meeting.
