### ISSUE TITLE
[DB] customer information

### ISSUE THREAD

**Issue by ranilplus** [ranilplus/Idac-Maintaenance#4]
Please chek if mising.
Customer id:auto generated unique  number
Customer name:this is also unique Ex Sampath Dehiwala supper
Type:coperate/home/ngo/contractor..
Address:
City:colombo 1,kandy
District:colombo
Rating:
Number of units.

**Comment by AthulaDissanayaka** [comment]
In case customer wants to include google map in to this? Are you  going to have it as a field? Customer name may not necessarily be unique as it's  a text field. Please comment on this.

**Comment by ranilplus** [comment]
Customer name: i mean unique as you can't add same name for two customer ids Ex you can't have two sampth dehiwala supper, next should be sampath dehiwala metro or dehiwal 2.
one customer can have many units,

google map location gose with Ac unit or the item, because some unit installed location different with billing address. eg: sampath bank petta having Atm at patte station, customer address is personal but unit is at office/ some where. also one customer can have many units in different locations.

we have to add contact information: Contact No, FaxNo, Email to this db.

**Comment by AthulaDissanayaka** [comment]
Yes, thanks I agree. Can you add contact details to the customer db. After that shall I send these fields to the customer for confirmation?

**Comment by ranilplus** [comment]
Yes sure.

**Comment by AthulaDissanayaka** [comment]
Please include the following fields to customer db. Not compulsary fields. If the customer is VAT registered then it has to be entered. 
1. Customer registration number
2. VAT registration number
3. SVAT number

**Comment by ranilplus** [comment]
we can use Customer id: as Customer registration number.
New field 

NBT : charged / paid by idac

**Comment by AthulaDissanayaka** [comment]
No Ranil this is customer business registration number something like vat registration number. If customer provides it then enter it for future reference.
