### ISSUE TITLE
[DB] Ac unit information

### ISSUE THREAD

**Issue by ranilplus** [ranilplus/Idac-Maintaenance#5]
Please check if missing.

Unit Id: auto generated unique number by new system
serial number: unique number currently they using as primary key comes with Ac unit manufacture. 
Owner: Customer id( link with customer db)
Model No:
Type; wall mount/ ceiling,...
Location: 1st floor, ATM,Manager room,....
Geo Location: google map points.
gas: R600/...
Rated AMPS
Running AMPS
Rated Volts
Operation Volts
Suction Pressure
Discharge Pressure
Room Temperature
Installed by:
Installed Date:
Checked By:
Date/ Time
Remarks:
service contract: Yes/NO, to identify currently having service contract,No: buy only.
service contract id: link with service contract Db

**Comment by AthulaDissanayaka** [comment]
I think we need add installation date. Service activation date can have in serevice contract db.

**Comment by ranilplus** [comment]
Yes we have add it.

**Comment by AthulaDissanayaka** [comment]
I have added installed date to units table. Can I send all these tables with field to idac for confirmation? Can you send me Samantha's caontact number and the email address if you have.

**Comment by ranilplus** [comment]
Installed by: and Installed Date: already in above list also Checked By: and checked Date/ Time also in above list. yes sure send those fields and ask if there are missing some thing or need to add. 

samantha 0112764000

*please remind about payments & server pc to Rohitha.

**Comment by ranilplus** [comment]
New fields 
Equipment type :Split / ENV/DRF/Package air cooled/package water cooled/ split inverter/ non inverter

Filing Cabinet reference:
